# Generated by Django 6.0.3 on 2026-06-15 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraccess',
            options={'permissions': [('access_users_module', 'Can access users module'), ('access_reports_module', 'Can access reports module')], 'verbose_name': 'User access', 'verbose_name_plural': 'User access'},
        ),
    ]
