# Generated by Django 6.0.4 on 2026-04-24 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0001_initial'),
        ('products', '0002_alter_brand_name_alter_category_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inventory',
            new_name='InventoryItem',
        ),
    ]
