# Generated by Django 6.0.4 on 2026-05-06 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0003_rename_inventoryitem_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
