# Generated by Django 6.0.3 on 2026-06-01 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0005_stockmovement_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'permissions': [('access_inventory_module', 'Can access inventory module')]},
        ),
    ]
