# Generated by Django 6.0.3 on 2026-06-01 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_brand_name_alter_category_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('access_products_module', 'Can access products module')]},
        ),
    ]
